networks:
  art_net:
    driver: bridge

services:
  # --- БАЗА ДАННЫХ ---
  art_generation_postgres:
    image: postgres:15-alpine
    container_name: art_generation_postgres
    restart: always
    networks:
      - art_net
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      # Упростили, чтобы не было ошибки "role -d"
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- КЭШ ---
  art_generation_redis:
    image: redis:7-alpine
    container_name: art_generation_redis
    restart: always
    networks:
      - art_net
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  # --- БЭКЕНД ---
  art_generation_backend:
    build:
      context: ..
      dockerfile: Docker_all/Dockerfile.backend
    container_name: art_generation_backend
    restart: always
    networks:
      - art_net
    depends_on:
      art_generation_postgres:
        condition: service_healthy
      art_generation_redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ../app:/app/app
      - ../alembic:/app/alembic
      - ../alembic.ini:/app/alembic.ini
    # Принудительно передаем прокси
    environment:
      - HTTP_PROXY=${GLOBAL_PROXY}
      - HTTPS_PROXY=${GLOBAL_PROXY}

  # --- ВОРКЕР (Celery) ---
  art_generation_celery_worker:
    build:
      context: ..
      dockerfile: Docker_all/Dockerfile.backend
    container_name: art_generation_celery_worker
    restart: always
    networks:
      - art_net
    entrypoint: []
    command: celery -A app.celery_app worker --loglevel=info --pool=solo
    depends_on:
      art_generation_redis:
        condition: service_healthy
      art_generation_postgres:
        condition: service_healthy
    env_file: .env
    environment:
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
      - HTTP_PROXY=${GLOBAL_PROXY}
      - HTTPS_PROXY=${GLOBAL_PROXY}
    volumes:
      - ../app:/app/app

  # --- ФРОНТЕНД ---
  art_generation_frontend:
    build:
      context: ..
      dockerfile: Docker_all/Dockerfile.frontend
      args:
        - VITE_API_URL=http://${VPS_IP:-localhost}:8000
    container_name: art_generation_frontend
    restart: always
    networks:
      - art_net
    ports:
      - "80:80"
    depends_on:
      - art_generation_backend
    env_file: .env

volumes:
  pgdata: