services:
  art_generation_postgres_local:
    image: postgres:15-alpine
    container_name: art_generation_postgres_local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-art_generate_db}
    volumes:
      - pgdata_local:/var/lib/postgresql/data

  art_generation_redis_local:
    image: redis:7-alpine
    container_name: art_generation_redis_local
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-""}

  art_generation_celery_local:
    build:
      context: ..
      dockerfile: Dockerfile.celery
    container_name: art_generation_celery_local
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://art_generation_redis_local:6379/0
      - REDIS_LOCAL=""
      - IS_DOCKER=true
      - PYTHONPATH=/app
    depends_on:
      - art_generation_redis_local
    volumes:
      - ../app:/app/app
    command: celery -A app.celery_app worker --loglevel=info --queues=high_priority,normal_priority,low_priority

  art_generation_celery_beat_local:
    build:
      context: ..
      dockerfile: Dockerfile.celery
    container_name: art_generation_celery_beat_local
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://art_generation_redis_local:6379/0
      - REDIS_LOCAL=""
      - IS_DOCKER=true
      - PYTHONPATH=/app
    depends_on:
      - art_generation_redis_local
    volumes:
      - ../app:/app/app
    command: celery -A app.celery_app beat --loglevel=info

volumes:
  pgdata_local:
